// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBh35bgruQLxRUK9m8guYMurCE19cIdoHs',
    appId: '1:159418645512:web:93f78ca7ad0b74ffe6a5bd',
    messagingSenderId: '159418645512',
    projectId: 'psu-tracker-app',
    authDomain: 'psu-tracker-app.firebaseapp.com',
    storageBucket: 'psu-tracker-app.firebasestorage.app',
    measurementId: 'G-HDKMWKXVXM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNrroPuDk0D-65SQiIkhlma2w6-ZCMMmU',
    appId: '1:159418645512:android:9938193b934be03fe6a5bd',
    messagingSenderId: '159418645512',
    projectId: 'psu-tracker-app',
    storageBucket: 'psu-tracker-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABHso-xwcJilUPF4OwgNR_G44jXgfi6Y4',
    appId: '1:159418645512:ios:f787d49bbbe6554be6a5bd',
    messagingSenderId: '159418645512',
    projectId: 'psu-tracker-app',
    storageBucket: 'psu-tracker-app.firebasestorage.app',
    iosBundleId: 'com.example.psuNotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABHso-xwcJilUPF4OwgNR_G44jXgfi6Y4',
    appId: '1:159418645512:ios:f787d49bbbe6554be6a5bd',
    messagingSenderId: '159418645512',
    projectId: 'psu-tracker-app',
    storageBucket: 'psu-tracker-app.firebasestorage.app',
    iosBundleId: 'com.example.psuNotification',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBh35bgruQLxRUK9m8guYMurCE19cIdoHs',
    appId: '1:159418645512:web:250dcec7fe4be6c9e6a5bd',
    messagingSenderId: '159418645512',
    projectId: 'psu-tracker-app',
    authDomain: 'psu-tracker-app.firebaseapp.com',
    storageBucket: 'psu-tracker-app.firebasestorage.app',
    measurementId: 'G-NW41K0XTRJ',
  );
}
